development:
  kmedia_url: 'http://localhost:4000'
  kmedia_user: 'ana@email.com'
  kmedia_password: '123456'


production:
  kmedia_url: 'http://kmedia.kbb1.com'
  kmedia_user: 'annamik@gmail.com'
  kmedia_password: 'mili10'


