development:
  kmedia_url: 'http://localhost:4000'
  kmedia_user: 'mylibrary@gmail.com'
  kmedia_password: 'mlke78951'
  library_url: 'mylibrary.kbb1.com'


production:
  kmedia_url: 'http://kmedia.kbb1.com'
  kmedia_user: 'mylibrary@gmail.com'
  kmedia_password: 'mlke78951'
  library_url: 'mylibrary.kbb1.com'


